_wandb:
    value:
        cli_version: 0.22.3
        e:
            2oln9q3bd1qfuyt6coxwc9uqz8y57uic:
                codePath: Downloads/DeepL/DeepL_Project/Test.py
                codePathLocal: Test.py
                email: 1634535941@qq.com
                executable: /Users/otis/Downloads/DeepL/DeepL_Project/ffnn_env/bin/python
                host: otisdeair.students.clients.local
                os: macOS-14.6-arm64-arm-64bit
                program: /Users/otis/Downloads/DeepL/DeepL_Project/Test.py
                python: CPython 3.12.8
                root: /Users/otis/Downloads/DeepL/DeepL_Project
                startedAt: "2025-11-06T17:02:02.788297Z"
                writerId: 2oln9q3bd1qfuyt6coxwc9uqz8y57uic
        m: []
        python_version: 3.12.8
        t:
            "3":
                - 16
            "4": 3.12.8
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
test_run:
    value: true
